AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Properties:
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Handler: index.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
      MemorySize: 1024
      Timeout: 120
    Type: AWS::Serverless::Function
  Table:
    Type: AWS::Serverless::SimpleTable
